<?php
$isEnable = $this->helper('Coderkube\Team\Helper\Data')->getConfig('team_tab/general/enable');
if ($isEnable == 1) :
  $collection = $block->getTeamCollection();
  $collectioncat = $block->getCategoryCollection();
?>
  <section id="sel">
    <div class="founders">
      <div class="container">
        <?php $i = 0;
        foreach ($collectioncat as $category) { ?>
          <div class="row">
            <div class="col-md-12">
              <div class="title 000">
                <h2><?php echo $category->getCategoryName(); ?></h2>
                <?php $a = $category->getCatId(); ?>
              </div>
            </div>
          </div>
          <div class="row">
            <?php
            foreach ($collection as $team) {
            ?>
              <?php $b = $team->getCategoryName(); ?>
              <?php if ($a == $b) { ?>
                <div class="col-md-4 col-xs-12">
                  <figure>
                    <figcaption>
                      <tr>
                        <div class="col image-block">
                          <?php if ($team->getImage()) : ?>
                            <img src="<?php echo $block->getMediaUrl() . $team->getImage(); ?>">
                          <?php else : ?>
                            <img src="<?php echo $block->getViewFileUrl('Coderkube_Team::images/place.jpeg'); ?>" />
                          <?php endif; ?>
                          <br>
                        </div>
                        <div class="col name">
                          <h3><?php echo $team->getMemberName(); ?></h3>
                        </div>
                        <div class="col designation"><span><?php echo $team->getDesignation(); ?></span></div>
                        <div class="col content show-read-more"><?php echo $team->getContent(); ?></div>
                        <div class="col mine">
                          <div class="social-container">
                            <ul class="social-icons">
                              <li><?php echo '<a href="mailto:' . $team->getEmailId() . '"' . 'target="_blank">'; ?> <i class="fa fa-envelope-square"></i></a></li>
                              <li><a href="https://www.facebook.com/<?php echo $team->getFbLink(); ?>" target="_blank"><i class="fa fa-facebook"></i></a></li>
                              <li><a href="https://www.linkedin.com/<?php echo $team->getGoogleLink(); ?>" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                              <li><a href="http://twitter.com/<?php echo $team->getTwitterLink(); ?>" target="_blank"><i class="fa fa-twitter"></i></a></li>
                            </ul>
                          </div>
                      </tr>
                    </figcaption>
                  </figure>
                </div>
              <?php } ?>
            <?php } ?>
          </div>
        <?php $i++;
        } ?>
      </div>
    </div>
  </section>
<?php else : echo "Extension is must be enable please enable your extension!"; ?>
<?php endif; ?>